version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/zeta-app-contracts"
      - "/packages/zevm-app-contracts"

    # VERSION UPDATES (scheduled)
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependabot: "
    labels: ["dependencies"]
    open-pull-requests-limit: 2   # limits *version* PRs; security PRs ignore this

    groups:
      # 1) ZetaChain packages together
      zetachain-version:
        patterns:
          - "@zetachain/addresses"
          - "@zetachain/toolkit"
          - "@zetachain/ui-toolkit"

      # 2) Everything else in one PR (exclude ZetaChain deps to avoid overlap)
      everything-else-version:
        patterns:
          - "*"
        exclude-patterns:
          - "@zetachain/addresses"
          - "@zetachain/toolkit"
          - "@zetachain/ui-toolkit"
        update-types:
          - "minor"
          - "patch"

      # SECURITY UPDATES (event-driven; schedule is ignored)
      zetachain-security:
        applies-to: security-updates
        patterns:
          - "@zetachain/addresses"
          - "@zetachain/toolkit"
          - "@zetachain/ui-toolkit"

      everything-else-security:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@zetachain/addresses"
          - "@zetachain/toolkit"
          - "@zetachain/ui-toolkit"
