name: Publish Blog Post to Telegram
on:
  pull_request:
    branches: [announcements]
    types: [closed]
    paths:
      - "announcements/*.md"
jobs:
  publish_to_telegram:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Identify Markdown Files
        id: files
        run: |
          base_sha=${{ github.event.pull_request.base.sha }}
          head_sha=${{ github.event.pull_request.head.sha }}
          files=$(git diff --name-only "$base_sha" "$head_sha" -- 'announcements/*.md')
          # Replace newline with comma
          files_comma_separated=$(echo "$files" | tr '\n' ',')
          echo "Changed Markdown Files: $files_comma_separated"
          echo "::set-output name=markdown_files::$files_comma_separated"

      - name: Publish to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        run: |
          echo "Publishing to Telegram..."
          IFS=',' read -ra files_arr <<< "${{ steps.files.outputs.markdown_files }}"
          for file in "${files_arr[@]}"; do
            # Skip empty strings which may occur if there's a trailing comma
            [ -z "$file" ] && continue
            echo "Processing file: $file"
            content=$(cat "$file")
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_TO}" -d text="$content" -d parse_mode="MarkdownV2"
          done
